language: C

install:
- wget https://nginx.org/download/nginx-1.16...
- tar -xf nginx-1.16.1.tar.gz 
- cd nginx-1.16.1/
- apt-get install build-essential
- ./configure 
- apt-get install zlib* gzip* libssl-dev
- ./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-pcre --pid-path=/var/run/nginx.pid
- make